echo "Abhi Sharma"
echo "user : $USER"


cd ~/Code/MCB185/data
gunzip -c dictionary.gz| grep -E "^[acuomtf]*a[acuotmf]*$" | grep .... 

gunzip -c dictionary.gz| grep -E "^[bialnrt]*b[bianlrt]*$" | grep .... 

gunzip -c dictionary.gz| grep -E "^[coamdin]*c[coamdin]*$" | grep .... 

gunzip -c dictionary.gz| grep -E "^[anoizgr]*z[anoizgr]*$" | grep .... 
